from utils.config_reader import ConfigReader
if __name__ == '__main__':
    config = ConfigReader()
    # print(config.get_num_workers())
    # print(config.get_fp16())
    # print(config.get_dataset_path())
    # print(config.need_divide())
    # print(config.get_divide_percent())
    # print(config.need_crop())
    # print(config.get_crop_size())
    # print(config.get_auto_color())
    # print(config.get_color_map())
    # print(config.need_color())
    # print(config.get_num_classes())
    # print(config.cls_weight_enable())
    # print(config.get_cls_weight())
    # print(config.get_random_seed())
    # print(config.cuda_enable())
    # print(config.get_cuda_mode())
    # print(config.get_cuda_visible_gpus())
    # print(config.get_cuda_master_gpu())
    # print(config.get_phi())
    # print(config.pretrained_enable())
    # print(config.get_pretrained_param())
    # print(config.freeze_train_enable())
    # print(config.get_epoch_param())
    # print(config.get_init_lr())
    # print(config.get_min_lr())
    # print(config.get_optimizer_param())
    # print(config.get_lr_decay_type())
    # print(config.get_input_size())
    print(config.focal_loss_enable())
    print(config.dice_loss_enable())
    print(config.eval_freq())
    print(config.get_log_dir())