;训练数据集配置项
;path: 训练数据位置
;need_annotation: 是否需要生成文件标注, 数据需要按照VOC数据集方式存放，此项标注为True将会生成VOC标准中的.txt文件
;train_percent: 训练集占所有数据的大小 total_data = train_data(训练集) + val_data(验证集) [need_annotation为True时生效]
;trainval_percent: 测试集，默认使用全部数据进行测试 [need_annotation为True时生效]
[train_data]
path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\train_data\VOCdevkit\VOC2012
need_annotation = False
train_percent = 0.9
trainval_percent = 1

;训练参数配置项

[model_train]
cuda = True
fp16 = False
seed = 0
num_classes = 20
feature_extraction_fun = b0
pretrained = True
backbone_pretrained = False
backbone_weight_path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\weights\segformer_b0_backbone_weights.pth
model_weight_path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\weights\segformer_b0_weights_voc.pth
input_shape = 512, 512
freeze_train = True
init_epoch = 0
freeze_epoch = 50
freeze_batch_size = 16
unfreeze_epoch = 100
unfreeze_batch_size = 8
init_lr = 1e-4
min_lr_rate = 0.01
optimizer_type = adamw
momentum = 0.9
weight_decay = 1e-2
lr_decay_type = cos
dice_loss = False
focal_loss = False
num_workers = 4
