;训练数据配置项
;path: 训练数据位置
;need_annotation: 是否需要生成文件标注, 数据需要按照VOC数据集方式存放，此项标注为True将会生成VOC标准中的.txt文件
;train_percent: 训练集占所有数据的大小 total_data = train_data(训练集) + val_data(验证集)
;trainval_percent: 测试集，默认使用全部数据进行测试
[train_data]
path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\train_data\VOCdevkit\VOC2012
need_annotation = False
train_percent = 0.9
trainval_percent = 1