;训练数据集配置项
;path: 训练数据位置
;need_annotation: 是否需要生成文件标注, 数据需要按照VOC数据集方式存放，此项标注为True将会生成VOC标准中的.txt文件
;train_percent: 训练集占所有数据的大小 total_data = train_data(训练集) + val_data(验证集) [need_annotation为True时生效]
;trainval_percent: 测试集，默认使用全部数据进行测试 [need_annotation为True时生效]
[train_data]
path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\train_data\VOCdevkit\VOC2012
need_annotation = False
train_percent = 0.9
trainval_percent = 1

;训练参数配置项
;cuda：是否使用GPU加速
;   False：使用cpu
;   True：使用gpu
;seed: 随机数种子，使得每次独立训练结果相同
;fp16: 是否使用混合精度训练，可以节约一定显存 （需要pytorch >= 1.7.1）
;   True：使用混合精度
;   False：不使用混合精度
;num_classes: 数据集中的分类个数 （实际的分类个数，不需要加上背景的1，程序会自动实现+1操作）
;feature_extraction_fun: 使用的特征提取函数的规模，在Segformer中有b0 ~ b5六档可选
;pretrained: 是否使用预训练权重
;   True：使用预训练权重
;   False：不使用预训练权重
;backbone_pretrained: 是否使用主干预训练权重 （只有pretrained=True,此项才生效；此项会加载主干[backbone]预训练权重, 如果为）
;   True：仅主干（backbone）加载预训练权重，需要backbone_weight_path不为空
;   False：模型将会全局加载预训练权重，需要model_weight_path不为空
;input_shape: 输入图片大小（并不是要求图片一定是这个尺寸，这个是模型训练中统一会把训练图片处理到的大小）

[model_train]
cuda = True
seed = 0
fp16 = False
num_classes = 20
feature_extraction_fun = b0
pretrained = True
backbone_pretrained = False
backbone_weight_path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\weights\segformer_b0_backbone_weights.pth
model_weight_path = E:\毕设\Cross_Domain_Few_Shot_Segmentation_System\data\weights\segformer_b0_weights_voc.pth
input_shape = 512, 512
freeze_train = True
init_epoch = 0
freeze_epoch = 50
freeze_batch_size = 16
unfreeze_epoch = 100
unfreeze_batch_size = 8
init_lr = 1e-4
min_lr_rate = 0.01
optimizer_type = adamw
momentum = 0.9
weight_decay = 1e-2
lr_decay_type = cos
dice_loss = False
focal_loss = False
num_workers = 4
